/*
  Creates a search button that call the github api
  and returns the data of the searched user

  The data is client side fetched
*/
import { useCallback, useRef, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'

const server = 'https://api.github.com'
const api_path = 'users'

type GithubUser = {
  login: string
  id: number
  node_id: string
  avatar_url: string
  gravatar_id: string
  url: string
  html_url: string
  followers_url: string
  following_url: string
  gists_url: string
  starred_url: string
  subscriptions_url: string
  organizations_url: string
  repos_url: string
  events_url: string
  received_events_url: string
  type: string
  site_admin: boolean
  name: string
  company: string
  blog: string
  location: string
  email: string
  hireable: boolean
  bio: string
  twitter_username: string
  public_repos: number
  public_gists: number
  followers: number
  following: number
  created_at: string
  updated_at: string
}

type Data = {
  name: string
  image_profile: string
}

const Home: NextPage = () => {
  // States
  let username_input: string = 'darkvictor13'
  const [data, setData] = useState<Data>({ name: 'Nome inicial', image_profile: '' })

  const onClickButton = async () => {
    username_input = (document.getElementById('username_input') as HTMLInputElement).value
    console.log('onClickButton with username_input: ', username_input)
    fetch(`${server}/${api_path}/${username_input}`)
      .then((res: Response) => res.json())
      .then((_data: GithubUser) => {
        setData({ name: _data.name, image_profile: _data.avatar_url })
      });
  }
  return (
      <div className={styles.container}>
        <Head>
          <title>Github Profile Card App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div>
            <input
              type='text'
              id = 'username_input'
            >
            </input>
            <button onClick={onClickButton}>
              Search
            </button>
          </div>
          <div>
            <a
            className={styles.card}
            href='https://github.com/${data.name}'
            >
              <h2>User</h2>
              <p>Name: {data.name}</p>
              <p>Image: {data.image_profile}</p>
            </a>
          </div>
        </main>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.tsx</code>
          </p>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    )
  }

  export default Home
