/*
  Creates a search button that call the github api
  and returns the data of the searched user

  The data is client side fetched
*/
import { useCallback, useRef, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import { type } from 'os'

const server = 'https://api.github.com'
const api_path = 'users'

type GithubUser = {
  login: string
  id: number
  node_id: string
  avatar_url: string
  gravatar_id: string
  url: string
  html_url: string
  followers_url: string
  following_url: string
  gists_url: string
  starred_url: string
  subscriptions_url: string
  organizations_url: string
  repos_url: string
  events_url: string
  received_events_url: string
  type: string
  site_admin: boolean
  name: string
  company: string
  blog: string
  location: string
  email: string
  hireable: boolean
  bio: string
  twitter_username: string
  public_repos: number
  public_gists: number
  followers: number
  following: number
  created_at: string
  updated_at: string
}

type Error = {
  message: string
  documentation_url: string
}

const Home: NextPage = () => {
  // States
  let username_input: string = '';
  const [is_data_valid, setIsDataValid] = useState<boolean>(false)
  const [data, setData] = useState<GithubUser>({
    login: '',
    id: 0,
    node_id: '',
    avatar_url: '',
    gravatar_id: '',
    url: '',
    html_url: '',
    followers_url: '',
    following_url: '',
    gists_url: '',
    starred_url: '',
    subscriptions_url: '',
    organizations_url: '',
    repos_url: '',
    events_url: '',
    received_events_url: '',
    type: '',
    site_admin: false,
    name: '',
    company: '',
    blog: '',
    location: '',
    email: '',
    hireable: false,
    bio: '',
    twitter_username: '',
    public_repos: 0,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: '',
    updated_at: ''
  })

  const onClickButton = async () => {
    username_input = (
      document.getElementById('username_input') as HTMLInputElement
    ).value
    if (username_input == '') {
      setIsDataValid(false)
      return
    }

    fetch(`${server}/${api_path}/${username_input}`)
      .then((res: Response) =>{
        if (!res.ok) {
          throw Error(res.statusText)
        }
        return res.json()
      }).then((_data: GithubUser) => {
        setIsDataValid(true)
        setData(_data)
      }).catch((error: Error) => {
        setIsDataValid(false)
      });
  }
  /*
    TODO:
      - Transformar em componente o card
      - Mostrar apenas campos que não são nulos ou vazios
      - Mostrar mensagem de erro caso o usuário não exista
      - Quando usuário for inválido, mostrar mensagem de erro
      - Animação de carregamento
  */
  return (
      <div className={styles.container}>
        <Head>
          <title>Github Profile Card App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div>
            <input
              type='text'
              id='username_input'
              placeholder='Nome do usuário'
              onKeyPress={(e) => {
                if (e.key === 'Enter') {
                  onClickButton()
                }
              }}
            />
            <button onClick={onClickButton}>
              Search 🔎
            </button>
          </div>

          <div className={styles.grid}>
            {is_data_valid?
              <a
              id='github_profile_card'
              className={styles.card}
              href={data.html_url}
              target='_blank'
              >
                <h2>User: {data.login}</h2>
                <img src={data.avatar_url} width={300} />
                <p><b>About:</b> {data.bio}</p>
                <p><b>Name</b>: {data.name}</p>
                <p><b>Company:</b> {data.company}</p>
                <p><b>Email:</b> {data.email}</p>
                <p><b>Followers:</b> {data.followers}</p>
                <p><b>Following:</b> {data.following}</p>
                <p><b>Public Repos:</b> {data.public_repos}</p>
                <p><b>Location: {data.location}</b></p>
              </a>
            : 
              <div></div>
            }
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    )
  }

  export default Home
